version: 2
updates:
  # npm依存関係の自動更新（セキュリティのみ・月次）
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 2 # PR数を制限
    assignees:
      - "@me"
    reviewers:
      - "@me"
    commit-message:
      prefix: "security"
      include: "scope"
    # セキュリティアップデートのみ許可
    allow:
      - dependency-type: "direct"
        update-types: ["security-update"]
      - dependency-type: "indirect"
        update-types: ["security-update"]
    # 通常のバージョンアップデートは除外
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"

  # GitHub Actionsの自動更新（月次）
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 1
